[settings]
asdf_compat = false
experimental = true
lockfile = false
go_default_packages_file = "~/.config/mise/default/golang"
go_set_gopath = true
jobs = 4
legacy_version_file = false
pipx_uvx = true
python_compile = true
python_default_packages_file = "~/.config/mise/default/python"
raw = false
status.show_env = true
trusted_config_paths = [ '~/.config/mise' ]

[tools]
deno = "latest"
go = "latest"
lua = "5.1"
node = "latest"
php = "8.4.4"
python = "latest"
ruby = "latest"
rust = "latest"
zig = "latest"
# ---
"aqua:phiresky/ripgrep-all" = "latest"
# ---
"cargo:eza" = "latest"
"cargo:vimv" = "latest"
# ---
"github:achristmascarl/rainfrog" = "latest"
"github:akiomik/mado" = "latest"
"github:astral-sh/uv" = "latest"
"github:boxdot/gurk-rs" = { version = "latest", extract_all = "true" }
"github:cargo-bins/cargo-binstall" = "latest"
"github:carthage-software/mago" = "latest"
"github:dandavison/delta" = "latest"
"github:jdx/usage" = "latest"
"github:junegunn/fzf" = "latest"
"github:symfony-cli/symfony-cli" = { version = "latest", exe = "symfony" }
"github:typst/typst" = "latest"
